name:                clash-prelude-extra
version:             0.1.0.0
github:              "IchiroKawashima/clash-prelude-extra"
license:             BSD3
author:              "Ichiro Kawashima"
maintainer:          "Kawashima.ichiro172@mail.kyutech.jp"
copyright:           "2020 Ichiro Kawashima"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/IchiroKawashima/clash-prelude-extra#readme>

dependencies:
- base
- clash-prelude
- ghc-typelits-extra
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- singletons
- singletons-th
- constraints
- extra

ghc-options:
- -fplugin=GHC.TypeLits.Extra.Solver
- -fplugin=GHC.TypeLits.Normalise
- -fplugin=GHC.TypeLits.KnownNat.Solver
- -fconstraint-solver-iterations=0
- -fexpose-all-unfoldings
- -fno-worker-wrapper
- -Wall
- -Wcompat

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- ExplicitForAll
- InstanceSigs
- KindSignatures
- LambdaCase
- NoImplicitPrelude
- NoStarIsType
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
- TemplateHaskell
- QuasiQuotes

library:
  source-dirs: src

tests:
  clash-prelude-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clash-prelude-extra
    - hspec
    - QuickCheck
