resolver: lts-15.14

packages:
- .

extra-deps:
- clash-ghc-1.2.4
- clash-lib-1.2.4
- clash-prelude-1.2.4
- concurrent-supply-0.1.8
- ghc-typelits-extra-0.4

flags:
  clash-prelude:
    large-tuples: false
