name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build
      run: stack build

    - name: Test
      run: stack test
